### ISSUE TITLE
add function edge cases

### ISSUE THREAD

**Issue by rgroshanrg** [kothariji/BhimIntegers#2]
`BhimInteger n("-350");
    BhimInteger n1("-35");
    n = n + n1;
    cout << n; // output => -085`

If we try to add -350 and -35 it gives -085, which is not correct.
Before actual addition in add function, the edge cases should be checked like if both numbers are negative or if one is negative and one is not and perform our expression accordingly.

**Comment by rgroshanrg** [comment]
If you permit me then I can Resolve it.

**Comment by kothariji** [comment]
Thank you for letting us know about this bug. Please feel free to resolve this.

**Comment by kothariji** [comment]
**FIXED**
