### ISSUE TITLE
Contribute adding new functions !!

### ISSUE THREAD

**Issue by kothariji** [kothariji/BhimIntegers#4]
Step 1 - Fork this repository.
Step 2 - Clone the repository to yuor local machine.
Step 3 - Resolve this bugs, mentions provided in the Issues section of the repository. Also add a description what changes you ahve done.
Step 4 - Add the changes to your repository.
Step 5 - Create a PULL Request. And that's all.

**Comment by rgroshanrg** [comment]
I can add power function. Should I?

**Comment by kothariji** [comment]
> I can add a power function. Should I?

Sure go ahead

**Comment by anurag341** [comment]
i can add abs function

**Comment by Coderu2058** [comment]
i can add abs function
