### ISSUE TITLE
User Input Handling.

### ISSUE THREAD

**Issue by rgroshanrg** [kothariji/BhimIntegers#6]
If User/Programmer gives invalid input then it doesn't check for the Validation or Handling the error.

For Example 
  ```
  BhimInteger a("--89");
    BhimInteger b("-70");
    cout << a + b;      // output => **--19**
```
It gives wrong output which is **--19** and this does not mean anything.

So, I would like to work on it and also would like to PR by checking the User Input and Handling, if you permit.

**Comment by kothariji** [comment]
Yes Nice!
